spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/PRODUCT_PURCHASE_DB
    username: postgres
    password: postgres

  messages:
    basename: error-messages

kafka:
  bootstrapAddress: localhost:9092

server:
  port: 8086

partitioned:
  topic:
    name: partitioned


